CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

CONFIG_ZMK_INPUT_AMS_AS5600=y
CONFIG_ZMK_INPUT_AMS_AS5600_SET_HID_RESOLUTION_MULTIPLIER=y
CONFIG_ZMK_INPUT_AMS_AS5600_HID_WHEEL_RESOLUTION=15
CONFIG_ZMK_INPUT_AMS_AS5600_LOG_AGC=n
CONFIG_ZMK_INPUT_AMS_AS5600_ACTIVE_POLL_INTERVAL=5
CONFIG_ZMK_INPUT_AMS_AS5600_IDLE_POLL_INTERVAL=500
CONFIG_ZMK_INPUT_AMS_AS5600_SENSOR_STARTUP_DELAY_MS=4
CONFIG_ZMK_INPUT_AMS_AS5600_INACTIVITY_TIMEOUT_MS=2000
CONFIG_ZMK_INPUT_AMS_AS5600_MOVEMENT_THRESHOLD=1
CONFIG_ZMK_INPUT_AMS_AS5600_SCROLL_SCALE_MULTIPLIER=1
CONFIG_ZMK_INPUT_AMS_AS5600_SCROLL_SCALE_DIVISOR=1
CONFIG_ZMK_INPUT_AMS_AS5600_HYSTERESIS_1LSB=y
CONFIG_ZMK_INPUT_AMS_AS5600_SLOW_FILTER_16X=y
CONFIG_ZMK_INPUT_AMS_AS5600_FAST_FILTER_THRESHOLD_7LSB=y



CONFIG_ZMK_USB_LOGGING=n

CONFIG_SETTINGS=y
CONFIG_SETTINGS_NVS=y

CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=3000
