CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

CONFIG_ZMK_INPUT_AMS_AS5600=y
CONFIG_ZMK_INPUT_AMS_AS5600_SET_HID_RESOLUTION_MULTIPLIER=y
CONFIG_ZMK_INPUT_AMS_AS5600_HID_WHEEL_RESOLUTION=15
CONFIG_ZMK_INPUT_AMS_AS5600_LOG_AGC=n
CONFIG_ZMK_INPUT_AMS_AS5600_ACTIVE_POLL_INTERVAL=5
CONFIG_ZMK_INPUT_AMS_AS5600_IDLE_POLL_INTERVAL=500
CONFIG_ZMK_INPUT_AMS_AS5600_SENSOR_STARTUP_DELAY_MS=4
CONFIG_ZMK_INPUT_AMS_AS5600_INACTIVITY_TIMEOUT_MS=2000
CONFIG_ZMK_INPUT_AMS_AS5600_MOVEMENT_THRESHOLD=1
CONFIG_ZMK_INPUT_AMS_AS5600_SCROLL_SCALE_MULTIPLIER=1
CONFIG_ZMK_INPUT_AMS_AS5600_SCROLL_SCALE_DIVISOR=1
CONFIG_ZMK_INPUT_AMS_AS5600_HYSTERESIS_2LSB=y
CONFIG_ZMK_INPUT_AMS_AS5600_SLOW_FILTER_16X=y
CONFIG_ZMK_INPUT_AMS_AS5600_FAST_FILTER_THRESHOLD_7LSB=y



CONFIG_ZMK_USB_LOGGING=n

CONFIG_SETTINGS=y
CONFIG_SETTINGS_NVS=y

CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=3000

# RGB LED Widget settings
CONFIG_RGBLED_WIDGET=y
CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y

# Timeout config for battery (1s)
CONFIG_RGBLED_WIDGET_BATTERY_BLINK_MS=1000

# Battery colors at 50% brightness
CONFIG_RGBLED_WIDGET_BATTERY_COLOR_HIGH=0x008000
CONFIG_RGBLED_WIDGET_BATTERY_COLOR_MEDIUM=0x808000
CONFIG_RGBLED_WIDGET_BATTERY_COLOR_LOW=0x800000
CONFIG_RGBLED_WIDGET_BATTERY_COLOR_CRITICAL=0x800000

# Sensitivity (Layers) LED Scaling - mapped to layers 0, 1, 2, 3
# Level 1: 50% Green
CONFIG_RGBLED_WIDGET_LAYER_0_COLOR=0x008000
# Level 2: 50% Blue
CONFIG_RGBLED_WIDGET_LAYER_1_COLOR=0x000080
# Level 3: 50% Yellow
CONFIG_RGBLED_WIDGET_LAYER_2_COLOR=0x808000
# Level 4: 50% Red
CONFIG_RGBLED_WIDGET_LAYER_3_COLOR=0x800000

